### ISSUE TITLE
Corregir Busquedas Externas

### ISSUE THREAD

**Issue by Stel0r** [Stel0r/ProyectoCienciasIIFinal#5]
El profe no fue nada especifico con este xd asi que aver que explota

**Comment by Stel0r** [comment]
Equipo 1 esta solucionando este issue junto a @AnnVil505 (Danna Villanueva)

**Comment by wulberri** [comment]
Yo encontré que al reiniciar, la tabla de abajo no se reinicia y se concatena la nueva tabla con la preexistente, además fui a buscar un número y crasheo
